//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Reply.Entity.Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 应答类型枚举
	/// </summary>
	/// <remarks>应答模式</remarks>
	public enum ReplyModeEnum : int
	{
		/// <summary>
		/// 丢弃处理0
		/// </summary>
		CAST,
		/// <summary>
		/// 同步处理1
		/// </summary>
		SYNCH,
		/// <summary>
		/// 异步处理2
		/// </summary>
		ASYNC,
		/// <summary>
		/// 转发处理3
		/// </summary>
		ROUTER,
		/// <summary>
		/// 中断阻塞4
		/// </summary>
		BREAK,
	}
}
